### PR TITLE
fix crash on  arm64 hook

### PR DESCRIPTION
**Pull request by dodola**
fix arm64 hook crash on my phone ,Xiaomi MIX2 ,smartisan

### CODE REVIEW

**Comment by BurntBrunch** [comment]
The logic here is definitely incorrect for arm. What makes you think it's correct for arm64?

**Comment by tophyr** [comment]
This change is incorrect: We pre-subtract `symoffset_` here so that we can avoid doing the subtraction at lookup time (thus making lookup ever-so-slightly faster). While this unfortunately results in fairly convoluted code, AOSP contains the optimization and we chose to keep AOSP's logic exactly as-is and just add copious documentation around the clever bits.

What is the crash you're seeing on arm64? All the tests pass on an API 24 arm64 emulator with GCC (Clang has some non-arch-related issues that we're working on); if you can send a repro or a test case that'd be greatly appreciated.

**Comment by dodola** [comment]
I dump some debug info 

crash info
```
A/libc: Fatal signal 11 (SIGSEGV), code 1, fault addr 0x839ea0580c in tid 6296 (ola.tracehooker)
A/DEBUG: *** *** *** *** *** *** *** *** *** *** *** *** *** *** *** ***
A/DEBUG: Build fingerprint: 'Rock/odin/odin:7.1.1/NMF26F/1524735354:user/dev-keys'
A/DEBUG: Revision: '0'
A/DEBUG: ABI: 'arm64'
A/DEBUG: pid: 6296, tid: 6296, name: ola.tracehooker  >>> com.dodola.tracehooker <<<
A/DEBUG: signal 11 (SIGSEGV), code 1 (SEGV_MAPERR), fault addr 0x839ea0580c
A/DEBUG:     x0   000000839ea0580c  x1   000000839ea05798  x2   00000000000003a0  x3   0000000000000003
A/DEBUG:     x4   0000000000000000  x5   0000000000000000  x6   0000007fa8933000  x7   0000000000000000
A/DEBUG:     x8   0000000000000000  x9   0000000000000000  x10  0000000000000000  x11  0000000000000036
A/DEBUG:     x12  0000000000000018  x13  0000000000000000  x14  0000000000000000  x15  000c43ad4efc4198
A/DEBUG:     x16  0000007fa88f6f08  x17  0000007fa88f47dc  x18  00000000ffffffff  x19  0000007f95c4ce60
A/DEBUG:     x20  0000007fa44acfd0  x21  0000007fa4a95a00  x22  0000007ff6eb4ffc  x23  0000007fa34dc58e
A/DEBUG:     x24  0000000000000000  x25  49d97a76bfc0aae8  x26  0000007fa4a95a98  x27  49d97a76bfc0aae8
A/DEBUG:     x28  0000000000000000  x29  0000007ff6eb44e0  x30  0000007f9cb01130
A/DEBUG:     sp   0000007ff6eb44e0  pc   0000007f9cb01164  pstate 0000000060000000
A/DEBUG: backtrace:
A/DEBUG:     #00 pc 0000000000070164  /data/app/com.dodola.tracehooker-1/lib/arm64/libnative-lib.so (_ZNK8facebook6linker16elfSharedLibData23gnu_find_symbol_by_nameEPKc+340)
A/DEBUG:     #01 pc 000000000006fd9c  /data/app/com.dodola.tracehooker-1/lib/arm64/libnative-lib.so (_ZNK8facebook6linker16elfSharedLibData19find_symbol_by_nameEPKc+44)
A/DEBUG:     #02 pc 00000000000582b0  /data/app/com.dodola.tracehooker-1/lib/arm64/libnative-lib.so (hook_single_lib+172)
A/DEBUG:     #03 pc 0000000000058808  /data/app/com.dodola.tracehooker-1/lib/arm64/libnative-lib.so (hook_all_libs+740)
A/DEBUG:     #04 pc 0000000000053bf8  /data/app/com.dodola.tracehooker-1/lib/arm64/libnative-lib.so (_ZN8facebook7profilo5hooks14hookLoadedLibsERKNSt6__ndk16vectorINS2_4pairIPKcPvEENS2_9allocatorIS8_EEEERNS2_13unordered_setINS2_12basic_stringIcNS2_11char_traitsIcEENS9_IcEEEENS2_4hashISJ_EENS2_8equal_toISJ_EENS9_ISJ_EEEE+1268)
A/DEBUG:     #05 pc 000000000004cec4  /data/app/com.dodola.tracehooker-1/lib/arm64/libnative-lib.so (_Z14hookLoadedLibsv+32)
A/DEBUG:     #06 pc 000000000004d5b4  /data/app/com.dodola.tracehooker-1/lib/arm64/libnative-lib.so (_Z22installSystraceSnooperv+1444)
A/DEBUG:     #07 pc 000000000004d864  /data/app/com.dodola.tracehooker-1/lib/arm64/libnative-lib.so (_Z19installSystraceHookv+12)
A/DEBUG:     #08 pc 000000000004d8f8  /data/app/com.dodola.tracehooker-1/lib/arm64/libnative-lib.so (Java_com_dodola_tracehooker_Atrace_installSystraceHook+16)
A/DEBUG:     #09 pc 000000000024713c  /data/app/com.dodola.tracehooker-1/oat/arm64/base.odex (offset 0x225000)
```




image


My test code is [https://github.com/dodola/fbhookfork](https://github.com/dodola/fbhookfork) 
But I found the following code in [Android linker source code](https://android.googlesource.com/platform/bionic/+/android-p-preview-2/linker/linker.cpp#3108) ,i think something wrong in my case

```c
  case DT_GNU_HASH:
        gnu_nbucket_ = reinterpret_cast<uint32_t*>(load_bias + d->d_un.d_ptr)[0];
        // skip symndx
        gnu_maskwords_ = reinterpret_cast<uint32_t*>(load_bias + d->d_un.d_ptr)[2];
        gnu_shift2_ = reinterpret_cast<uint32_t*>(load_bias + d->d_un.d_ptr)[3];

        gnu_bloom_filter_ = reinterpret_cast<ElfW(Addr)*>(load_bias + d->d_un.d_ptr + 16);
        gnu_bucket_ = reinterpret_cast<uint32_t*>(gnu_bloom_filter_ + gnu_maskwords_);
        // amend chain for symndx = header[1]
        gnu_chain_ = gnu_bucket_ + gnu_nbucket_ -
            reinterpret_cast<uint32_t*>(load_bias + d->d_un.d_ptr)[1];//this line

```

**Comment by tophyr** [comment]
Awesome, thanks for those memory dumps. It definitely looks like it's parsing the `.gnu.hash` section correctly, but I can't tell if the `chains_` list contains sane data. Would you mind pulling `/system/lib64/libwebviewchromium_plat_support.so` off your device and attaching it here?

**Comment by dodola** [comment]
The following file
[libwebviewchromium_plat_support.so.zip](https://github.com/facebookincubator/profilo/files/2037599/libwebviewchromium_plat_support.so.zip)

**Comment by tophyr** [comment]
Hey @dodola, sorry for going silent a bit on this one. I just took a look at that .so file and can't find anything too wonky about its DT_GNU_HASH section. Were you able to figure out the problem? If not, what symbol name are you looking up in it?

**Pull request closed without merging**
